name: FDWaterCardServer

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: commit #上传新的refresh_token
        run: |
          git config --global user.email 1994769112@qq.com
          git config --global user.name Demontisa
          git add getLeftMoney.json lastUpdate
          git commit -m "update new json" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:Demontisa/fdwater-card-server.git
          ssh_private_key:
            ${{ secrets.GITEE_KEY }}

      - name: Build Gitee Pages
        uses: Deomntisa/gitee-pages-action@master
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: 17607611914
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: Demontisa/fdwater-card-server
          branch: main 
